### ISSUE TITLE
Change use of get_cmap to matplotlib.colormaps

### ISSUE THREAD

**Issue by yonMaor** [vinsburg/alluvial_diagram#11]
The function get_cmap is going to be deprecated in future versions of matplotlib (we're currently getting a warning for this when running our examples). 

We should start using matplotlib.colomaps instead in AlluvialTool.get_color_array()

**Comment by vinsburg** [comment]
I'll try to look into it too, feel free to propose a solution!

**Comment by vinsburg** [comment]
resolved in [latest commit](https://github.com/vinsburg/alluvial_diagram/pull/15/commits/1e8af0ea80d68ec2af6598d6d5c279f72b369444)
