### ISSUE TITLE
Example 1 doesn't work in Python 3.6

### ISSUE THREAD

**Issue by maxtschochner** [vinsburg/alluvial_diagram#3]
Function in line 75 doesn't distinguish correctly between dict and list.

Suggestion for modification:
def read_input(self):
        if isinstance(self.input, list):
            return self.read_input_from_list()
        elif isinstance(self.input, dict):
            return self.read_input_from_dict()
        else:
            print('input type not correct')

**Comment by vinsburg** [comment]
Resolved in https://github.com/vinsburg/alluvial_diagram/commit/38916df52234ba551c5d19ee6b5a0a57739663ab

Please let me know if you experience anymore problems
